### ISSUE TITLE
Spotify Link doesn't work... at all...

### ISSUE THREAD

**Issue by ItsPugle** [Snuggle/Sprinkly#2]
On the site, the Spotify link goes to https://spotify.com/sunggle. Spotify's user pages are based on :spotify:user:{Username or GID}, so you'll be looking for this link instead: https://open.spotify.com/user/sunggle.

Also, you have like one public playlist :p

![Spotify Linking](https://monosnap.com/file/BYDyxDgKJkkmj24rrGoUiTECZC1MKC.png)

**Comment by Snuggle** [comment]
Ah, crud. xD

This repository is out of date, too, so I'll update it.

**Comment by Snuggle** [comment]
Fixed! Thank you for reporting. c:

**Comment by ItsPugle** [comment]
Easy-peasy-lemon-squeezy! Happy to help!
